name: Bump version
on:
  workflow_run:
    workflows: ['Test, check, lint']
    branches: [master]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    if: >
      ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: '0'
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.73.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: patch
        DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
